FROM python:3.12-slim AS builder

WORKDIR /app


COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir --prefix=/install -r requirements.txt


FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq5 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app


COPY --from=builder /install /usr/local

COPY app/bot ./app/bot
COPY app/database ./app/database
COPY app/utils ./app/utils
COPY app/__init__.py ./app/__init__.py
COPY reminder_system.py ./

ENV PYTHONPATH="/app"








