FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY reminder_system.py ./

COPY app/database ./app/database
COPY app/utils ./app/utils
COPY app/bot ./app/bot

ENV PYTHONPATH="/app"
